config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :employees
  resources :checkinouts
  resources :ref_documents
  resources :leaves, only: [:new, :index]
  root 'employees#index'
  
  get    '/login',   	          to: 'session#new'
  post   '/login',   	          to: 'session#create'
  get 	 '/logout',  	          to: 'session#destroy'
  get 	 '/employees/new',	    to: 'employees#new'
  get 	 '/employees',	        to: 'employees#index'
  get    '/attendances',        to: 'checkinouts#index'
  get    '/lates',              to: 'checkinouts#late_report'
  post   '/leaves/new',         to: 'leaves#create'
  get    '/leave_report',       to: 'leaves#leave_report'
  post   '/deleteDoc',          to: 'employees#deleteDocument'
  post   '/download_pdf',       to: 'employees#download_pdf'
 	
 end

app/models/checkinout.rb
class Checkinout < ApplicationRecord
	belongs_to	:user
end

app/controllers/checkinouts_controller.rb
class CheckinoutsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @Home = 'Late Management'
    @Link = 'Late Arrival List'
    beginning_of_month = Date.today.beginning_of_month
    end_of_month = beginning_of_month.end_of_month
    @attendances = Checkinout.all.joins(:user)
      .select("checkinouts.*,users.fullname").order(id: :desc)
      .where(date: beginning_of_month..end_of_month)
      .paginate(page: params[:page], per_page: 10)
  end

  def late_report
    @Home = 'Late Management'
    @Link = 'Late Arrival Report'
    @beginning_of_month = Date.today.beginning_of_month
    @end_of_month = @beginning_of_month.end_of_month
    @salary = 200000
    @users = User.all.joins(:employees).select("users.*, employees.employee_no")
  end


end

app/views/checkinouts/index.html.erb
<div class="card main-card">
	<div class="card-header">
		<h2>Attendance List</h2>
	</div>

	<div class="card-body">

		<table class="table table-sm table-hover table-bordered mb-3 mt-3">
			<thead>
	      <tr>
	      	<th>Name</th>
	        <th>Date</th>
	        <th>Time In</th>
	        <th>Time Out</th>
	        <th>Work Hour</th>
	        <!-- <th>Action</th>         -->
	      </tr>
	    </thead>
	    <tbody>
	    	<% @attendances.each do |attendance| %>
	      <tr>
	        <td><%= attendance.fullname %></td>
	        <td><%= attendance.date.strftime('%d-%b-%Y')  %></td>
	        <td><%= attendance.timeIn.strftime('%H:%M') %></td>
	        <td><%= attendance.timeOut.strftime('%H:%M') %></td>
	        <td><%= attendance.workHour.strftime('%H:%M') %></td>
	        <!-- <td>
	        	<%#= link_to '<i class="icon-eye"></i>'.html_safe, checkinout_url(:id => attendance.id, :show => attendance.id), :class => 'btn btn-info' %>
	        	<%#= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_checkinout_path(attendance), :class => 'btn btn-info' %>
	        	<%#= link_to '<i class="fa fa-close"></i>'.html_safe, attendance, method: :delete, data: { confirm: 'Are you sure do you want to delete?' }, :class => 'btn btn-danger' %>
	        </td> -->
	      </tr>
	      <% end %>
	    </tbody>
		</table>

		<div class="row justify-content-center">
			<%= will_paginate @attendances %>
		</div>

	</div>
</div>

app/views/checkinouts/late_report.erb
<div class="card main-card">
	<div class="card-header">
		<h2>Attendance List</h2>
	</div>

	<div class="card-body">

		<table class="table table-sm table-hover table-bordered mb-3 mt-3">
			<thead>
	      <tr>
	      	<th>Employee No</th>
	        <th>Name</th>
	        <th>Late Amount</th>
	      </tr>
	    </thead>
	    <% @users.each do |user| %>
	    <tbody>
	      <tr>
	        <td><%= user.employee_no %></td>
	        <td><%= user.fullname  %></td>
	        <% 
		       	@late_reports = Checkinout.where(:user_id => user.id,
		       									date: @beginning_of_month..@end_of_month)
		       	@late_amount = 0
		       	first_late = DateTime.parse("08:31:00").strftime('%H:%M:%S')
		          second_late = DateTime.parse("09:00:00").strftime('%H:%M:%S')
		       	@late_reports.each do |late_report|
		          time_in = late_report.timeIn.strftime('%H:%M:%S')
		          if time_in.between?( first_late, second_late ) 
		            @late_amount += 1000
		          elsif time_in > second_late 
		            @late_amount += (@salary/20)/2 
		          end
		       	end
	    		%>
	    		<td><%= number_to_currency(@late_amount, unit: "MMK ", precision: 3)
 %></td>
	      </tr>
	    </tbody>
	    <% end %>
		</table>

		<div class="row justify-content-center">
			<%#= will_paginate @users %>
		</div>

	</div>
</div>