config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :employees
  resources :checkinouts
  resources :ref_documents
  resources :leaves, only: [:new, :index]
  root 'employees#index'
  
  get    '/login',   	          to: 'session#new'
  post   '/login',   	          to: 'session#create'
  get 	 '/logout',  	          to: 'session#destroy'
  get 	 '/employees/new',	    to: 'employees#new'
  get 	 '/employees',	        to: 'employees#index'
  get    '/attendances',        to: 'checkinouts#index'
  get    '/lates',              to: 'checkinouts#late_report'
  post   '/leaves/new',         to: 'leaves#create'
  get    '/leave_report',       to: 'leaves#leave_report'
  post   '/deleteDoc',          to: 'employees#deleteDocument'
  post   '/download_pdf',       to: 'employees#download_pdf'
 	
 end

app/models/employee.rb
class Employee < ApplicationRecord
	mount_uploader :profile_image, ProfileImageUploader
	has_many		:ref_documents
	belongs_to 	:country
	belongs_to	:user
  accepts_nested_attributes_for :ref_documents

  validates :user_id, presence: true,
            uniqueness: {case_sensitive: false}
	validates :father_name, presence: true
  VALID_PHONE_REGEX = /^(0[1-9]|1[012])\-(19|20)\d{2}$/
  validates :contact_number, :presence => {:message => 'hello world, bad operation!'},
                       :numericality => true,
                       :length => { :minimum => 7, :maximum => 15 }
  validates :nrc, presence: true,
            uniqueness: { case_sensitive: false }
  validates :employee_no, presence: true,
  					uniqueness: { case_sensitive: false }
  validates :gender, presence: true
	validates	:nationality, presence: true
	validates :dob, presence: true
	validates :address, presence: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create, :update, :destroy]
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  def index
    @Home = 'Employee Home'
    @Link = 'Employee List'
    @roles = Role.all
    @employees = Employee.joins(:user)
      .select("employees.*,users.fullname,email,role_id").order(id: :desc)
      .paginate(page: params[:page], per_page: 10)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @Home = 'Employee Home'
    @Link = 'Employee Details'
    @employee_attachments = @employee.ref_documents.all
    @employee = Employee.joins(:user).select('employees.*, users.email').find(params[:id])
    @readonly = false
    if params[:show]
      @readonly = true
    end
    @male,@female = false
    if @employee.gender == 0
      @female = true
    elsif @employee.gender == 1
      @male = true
    end
  end

  # GET /employees/new
  def new
    @Home = 'Employee Home'
    @Link = 'Registration'
    @employee = Employee.new
    @employee_attachment = @employee.ref_documents.build
    @roles = Role.all
  end

  # GET /employees/1/edit
  def edit
    @Home = 'Employee Home'
    @Link = 'Employee Update'
    @employee_attachments = @employee.ref_documents.all
    @employee = Employee.joins(:user).select('employees.*, users.email').find(params[:id])
    @readonly = false
    if params[:show]
      @readonly = true
    end
    @male,@female = false
    if @employee.gender == 0
      @female = true
    elsif @employee.gender == 1
      @male = true
    end
  end

  # POST /employees
  # POST /employees.json
  def create

    @employee = Employee.new(employee_params)
    @employee[:country_id] = params[:employee][:country_id]
    @employee[:user_id] = params[:employee][:user_id]

    respond_to do |format|
      if @employee.save
        params[:ref_documents]['file_name'].each do |a|
          @employee_attachment = @employee.ref_documents.create!(:file_name => a)
        end
        @user = User.find(params[:employee][:user_id])
        @user.update(email: params[:employee][:email], password: params[:employee][:password])
        format.html { redirect_to employee_path(id:@employee.id, show:@employee.id) }
        format.json { render :show, status: :ok, location: @employee }
      else 
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end 

  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    @employee[:country_id] = params[:employee][:country_id]
    @employee[:user_id] = params[:employee][:user_id]
    
    respond_to do |format|
      if @employee.update(employee_params)

        params[:ref_documents]['file_name'].each do |a|
          @employee_attachment = @employee.ref_documents.update(:file_name => a)
        end

        @user = User.find(params[:employee][:user_id])
        @user.update(email: params[:employee][:email], password: params[:employee][:password])

        format.html { redirect_to edit_employee_path(id:@employee.id, show:@employee.id) }
        format.json { render :show, status: :ok, location: @employee }        

      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
 
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
  	respond_to do |format|
      if @employee.destroy
        format.html { redirect_to @employee }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def deleteDocument
    @ref_doc = RefDocument.find(params[:document_id])
    @ref_doc.destroy
    render :json => @ref_doc.to_json
  end

  def download_pdf
    ref_doc = RefDocument.find(params[:document_id])
    send_file(
      "#{Rails.root}/public#{ref_doc.file_name}",
      filename: "#{ref_doc.file_name}.pdf",
      type: "application/pdf"
    )
    render :json => ref_doc.to_json
  end

	private

    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit( :employee_no, :user_id, :father_name, :nationality,
       :gender, :nrc, :contact_number, :age, :dob, :address, :profile_image,
       :martial_status, :country_id, :fullname, ref_documents_attributes: [:id, :file_name] )
    end

end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: @employee, local: true, :html => {multipart: true} ) do |form| %>
	
	<div class="card">
    <div class="card-header">
      Personal Particulars
    </div>
    <div class="card-body">

      <div class="form-row">
        <div class="col-md-2 mb-3">
          <% if params[:show] %>
            <% if @employee.profile_image_url %>
              <%= image_tag @employee.profile_image_url, :size => '150x150', :class => 'border' %>
            <% end %>
          <% elsif params[:edit] %>
            <% if @employee.profile_image_url %>
              <%= form.file_field :profile_image, :class => "visually-hidden" %>
              <label for="employee_profile_image"><%= image_tag @employee.profile_image_url, :size => '150x150', :class => 'border' %></label>
            <% else %>
              <%= form.file_field :profile_image, :class => "visually-hidden" %>
              <label for="employee_profile_image"><img src="/img/employee/default.png" height="150" width="150" class="border"></label>
            <% end %>
          <% else %>
            <%= form.file_field :profile_image, :class => "visually-hidden" %>
            <label for="employee_profile_image"><img src="/img/employee/default.png" height="150" width="150" class="border"></label>
          <% end %>
        </div>
        <p class='error'><%= show_errors(@employee, :profile_image) %></p>
      </div>

      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="employee_no">Employee No</label>
          <%= form.text_field :employee_no, :class => "form-control", readonly: @readonly %>
          <p class='error'><%= show_errors(@employee, :employee_no) %></p>
        </div>
        <div class="col-md-4 mb-3">
          <label for="name">Name</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="icon-user"></i></span>
            </div>
	          <%= form.select :user_id, User.all.where("role_id != ?", 6).collect {|p| [ p.fullname,	p.id] }, { :include_blank => "Select" }, {:class => "form-control custom-select", :disabled => @readonly } %>
          </div>
          <p class='error'><%= show_errors(@employee, :user_id) %></p>
        </div>
        <div class="col-md-4 mb-3">
          <label for="gender">Gender</label>
          <div class="form-row">
            <div class="form-check-inline">
			      	<%= form.radio_button :gender, 1, :checked => @male, disabled: @readonly %> 
			  			<%= label :gender, 'Male' %>
				    </div>
				    <div class="form-check-inline">
				    	<%= form.radio_button :gender, 0, :checked => @female, disabled: @readonly %>
			  			<%= label :gender, 'Female' %>
				    </div>
          </div>
          <p class='error'><%= show_errors(@employee, :gender) %></p>
        </div>
      </div>

      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="father_name">Father Name</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="icon-user"></i></span>
            </div>
            <%= form.text_field :father_name, :class => "form-control", readonly: @readonly %>
         </div>
         <p class='error'><%= show_errors(@employee, :father_name) %></p>
        </div>
        <div class="col-md-4 mb-3">
          <label for="nationality">Nationality</label>
          <%= form.text_field :nationality, :class => "form-control", readonly: @readonly %>
        </div>
        <div class="col-md-4 mb-3">
          <label for="nrc">NRC</label>
          <%= form.text_field :nrc, :class => "form-control", readonly: @readonly %>
          <p class='error'><%= show_errors(@employee, :nrc) %></p>
        </div>
      </div>

      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="birth_country">Birth Country</label>
          <%= form.select :country_id, Country.all.collect {|p| [ p.name,
       		p.id] }, { :include_blank => "Select"}, {:class => "form-control custom-select", :disabled => @readonly } %>
          <p class='error'><%= show_errors(@employee, :country_id) %></p>
      	</div>
        <div class="col-md-4 mb-3">
          <label for="dob">Date of Birth</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="icon-calendar"></i></span>
            </div>
            <%= form.text_field :dob, :class => "form-control datepicker", readonly: @readonly %>
          </div>
          <p class='error'><%= show_errors(@employee, :dob) %></p>
        </div>
        <div class="col-md-4 mb-3">
          <label for="age">Age</label>
          <%= form.text_field :age, :class => "form-control", readonly: @readonly %>
          <p class='error'><%= show_errors(@employee, :age) %></p>
        </div>
      </div>

      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="martial_status">Martial Status</label>
          <%= form.select :martial_status,  options_for_select([['Single', 0], ['Marry', 1]], :selected => @employee.martial_status) , {include_blank: "Select"}, {:class => "form-control custom-select", :disabled => @readonly } %>
          <p class='error'><%= show_errors(@employee, :martial_status) %></p>
         </div>
        <div class="col-md-4 mb-3">
          <label for="contact_number">Contact Number</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <% if params[:show] %>
                <select class="form-control custom-select" name="contact_code" disabled>
                  <option value="1" selected>+95</option>
              <% else %>
                <select class="form-control custom-select" name="contact_code" >
                  <option selected>select</option>
              <% end %>
                <option value="1">+95</option>
              </select>
            </div>
            <%= form.text_field :contact_number, :class => "form-control", readonly: @readonly %>
            <p class='error'><%= show_errors(@employee, :contact_number) %></p>
          </div>

        </div>
        <div class="col-md-4 mb-3">
          <label for="email">Email</label>
          <%= form.text_field :email, :class => "form-control", readonly: @readonly %>
          <p class='error'><%= show_errors(@employee, :email) %></p>
        </div>
      </div>

      <% if !params[:show] && !params[:edit] %>
      <div class="form-row">
        <div class="col-md-4 mb-3">
          <label for="email">Password</label>
          <%= form.password_field :password, :class => "form-control", readonly: @readonly %>
          <p class='error'><%= show_errors(@employee, :password) %></p>
        </div>
        <div class="col-md-4 mb-3">
          <label for="email">Confirm Password</label>
          <%= form.password_field :password_confirmation, :class => "form-control", readonly: @readonly %>
        </div>
      </div>
      <% end %>

      <div class="form-row">
        <div class="col-md-8 mb-3">
          <label for="address">Address</label>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="icon-home"></i></span>
            </div>
            <%= form.text_area :address, :class => "form-control", readonly: @readonly %>
         </div>
         <p class='error'><%= show_errors(@employee, :address) %></p>
        </div>
      </div>

    </div>
	</div>

  <div class="card">
    <div class="card-header">
      Reference Document
    </div>
    <div class="card-body">

      <div class="row" style="cursor: pointer; width: 50%; color: #2895f1; margin-left:10px;">

        <% if !params[:show] %>
          <%= form.fields_for :ref_documents do |p| %>
            <%= p.file_field :file_name, :multiple => true, name: "ref_documents[file_name][]", :class => "visually-hidden", :onchange =>"handleFiles(this.files)" %>
            <%= p.label :file_name, '<img src="/img/employee/upload.png" class="file-image">Upload'.html_safe %>
          <% end %>
        <% end %>

        <% if params[:show] %>
          <a class="col-sm-3" id="downloadFile">
            <img src="/img/employee/download.png" class="file-image"> Download
          </a>
        <% end %>

        <% if !params[:show] %>
          <a class="col-sm-3" id="deleteFile">
            <img src="/img/employee/delete.png" class="file-image"> Delete
          </a>
        <% end %>

      </div>

      <div class="row">
        <table id="file-table" class="table table-bordered" >
          <thead>
            <tr>
              <th id="file-upload">File Name</th>
              <th>Modified</th>
            </tr>
          </thead>
          <tbody>
            <% if params[:show] %>
              <% @employee_attachments.each do |p| %>
              <tr class="" id="<%= p.id %>">
                <td><%= p.file_name_url %></td>
                <td><%= p.created_at.strftime('%d-%b-%Y') %></td>
              </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
        <p id="file_message" class="text-success"></p>
      </div>

    </div>

  </div>

  <div class="form-row">
    <% if params[:show] %>
    	<div class="col-md-6 col-sm-6">
        <a href="/employees" class="btn btn-light float-left"><i class="fa fa-times"></i>Back to List</a>
    	</div>
    <% else %>
      <div class="col-md-6 col-sm-6">
        <a href="/employees" class="btn btn-light float-left"><i class="fa fa-times"></i>Cancel</a>
      </div>
      <div class="col-md-6 col-sm-6">
      	<% if params[:id] %>
      		<%= form.submit "Update", :class => 'btn btn-primary float-right' %>
      	<% else %>
      		<%= form.submit "Save", :class => 'btn btn-primary float-right' %>
        <% end %>
      </div>
    <% end %>
  </div>

<% end %>


<script type="text/javascript">

  $(document).ready(function(){

    if ( $('input').is('[readonly]') ) { 
      $("#employee_dob").removeClass("datepicker");
    } else {
      $("#employee_dob").addClass("datepicker");
    }

    // Date picker
    $('.datepicker').datepicker({format: 'dd-M-yyyy'});

    // Table Click 
    $(document).on("click", "#file-table tbody tr", function(e) {
      var selected = $(this).hasClass("highlight");
      $("#file-table tr").removeClass("highlight");
      if(!selected)
        $(this).addClass("highlight");
    });

    $("#deleteFile").on("click", function(){
      var selectedFile = $("#file-table tr").hasClass("highlight");
      if(selectedFile) {
        var id = $("#file-table tr.highlight").attr("id");
        $.ajax({
          type: "POST",
          url: "/deleteDoc",
          data: {document_id: id},
          success: function(data){
            $('#file_message').text('Delete successfully');
          },
          error: function (error) {
            console.log(eval(error));
          }
        });
        $("#file-table tr.highlight").remove();
      } else {
        alert("Please select one file");
      }
    })

    $('#downloadFile').on('click', function(){
      var selectedFile = $("#file-table tr").hasClass("highlight");
      if(selectedFile) {
        var id = $("#file-table tr.highlight").attr("id");
        $.ajax({
          type: "POST",
          url: "/download_pdf",
          data: {document_id: id},
          success: function(data){
            $('#file_message').text('Download successfully');
          },
          error: function (error) {
            console.log(eval(error));
          }
        });
      } else {
        alert('Please choose one file');
      }

    })

  });

  function handleFiles(files) {
    // Current Date
    var dateFormat = new Date();
    var today = dateFormat.getFullYear() + "/" + (dateFormat.getMonth()+1) + "/" + dateFormat.getDate() + " " + dateFormat.getHours() + ":" + dateFormat.getMinutes() + ":" + dateFormat.getSeconds();;

    const table = $("#file-table");
    const tr = document.createElement("tr");
    const td1 = document.createElement("td");
    const td2 = document.createElement("td");
    
    for (let i = 0; i < files.length; i++) {
      const file = files[i];

      var myfile =$('#employee_ref_documents_attributes_0_file_name').val();
      var filename = myfile.replace(/.*(\/|\\)/, '')
      var ext = myfile.split('.').pop();

      if(ext == "pdf" || ext == "docx" || ext == "doc"){
        td1.append(filename);
        td2.append(today)
        tr.append(td1, td2);
        table.append(tr);
      } else{
        alert("Just upload pdf and doc.");
      }
    }

  }

</script>

app/views/employees/edit.html.erb
 <div class="card main-card">
	<div class="card-header">
		<h2>Edit Employee Registration</h2>
	</div>
	<div class="card-body">
		<%= render 'form', employees: @employee %>
	</div>
</div>

app/views/employees/index.html.erb
<% content_for :heading do 'User Detail' end %>

<div class="card main-card">
	<div class="card-header">
		<h2>Employee List</h2>
	</div>

	<div class="card-body">

		<!-- <div class="row">
      <div class="col-md-12">
          <a href="/employees/new" class="btn btn-info pull-right"><i class="fa fa-plus"></i> Create New</a>
      </div>
  	</div>

	  <div class="row">
	    <div class="col-md-3 mb-3">
	      <label for="employee_no">Employee No</label>
	      <input type="number" class="form-control" id="employee_no" name="employee_no" value="">
	    </div>
	    <div class="col-md-3 mb-3">
	      <label for="emp_type">Employee Type</label>
	      <%#= collection_select(:name, :id, @roles, :id, :name, {:prompt=>true}, {:class=>'form-control custom-select'} ) %>
	    </div>
	    <div class="col-md-3 mb-3">
	      <label for="name">Name</label>
	      <input type="text" class="form-control" id="name" name="name" value="">
	    </div>
	    <div class="col-md-3 mb-3">
	    	<a id="search" class="btn btn-info pull-left mt-4 ml-4">
          <img src="/img/search.png" style="height:20px;">
      	</a>
	    	<a id="ClearFilter" class="btn btn-info pull-left mt-4 ml-4" href="employees">
          <img src="/img/clear-filter.png" style="height:20px;">
      	</a>
	    </div>
	  </div> -->

		<table class="table table-sm table-hover table-bordered mb-3 mt-3">
			<thead>
	      <tr>
	        <th>Employee No</th>
	        <th>Employee Type</th>
	        <th>Name</th>
	        <th>Contact Number</th>
	        <th>Email Address </th>
	        <th>Action</th>
	      </tr>
	    </thead>
	    <tbody>
	    	<% @employees.each do |employee| %>
	    	<% puts employee %>
	      <tr>
	        <td><%= employee.employee_no %></td>
	        <td>
	        	<% @role = Role.find_by_id(employee.role_id) %>
	         	<%= @role.name %>
	        </td>
	        <td><%= employee.fullname %></td>
	        <td><%= number_to_phone(employee.contact_number, country_code: 95) %></td>
	        <td><%= employee.email %></td>
	        <td>
	        	<%= link_to '<i class="icon-eye"></i>'.html_safe, employee_url(:id => employee.id, :show => employee.id), :class => 'btn btn-info' %>
	        	<%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_employee_path(employee, :edit => employee.id), :class => 'btn btn-info' %>
	        	<%= link_to '<i class="fa fa-close"></i>'.html_safe, employee, method: :delete, data: { confirm: 'Are you sure do you want to delete?' }, :class => 'btn btn-danger' %>
	        </td>
	      </tr>
	      <% end %>
	    </tbody>
		</table>

		<div class="row justify-content-center">
			<%= will_paginate @employees %>
		</div>

	</div>
</div>

app/views/employees/new.html.erb
<div class="card main-card">
	<div class="card-header">
		<h2>Employee Registration</h2>
	</div>
	<div class="card-body">
		<%= render 'form', employees: @employee %>
	</div>
</div>

app/views/employees/show.html.erb
<div class="card main-card">
	<div class="card-header">
		<h2>Employee Detail</h2>
	</div>
	<div class="card-body">
		<%= render 'form', employees: @employee %>
	</div>
</div>