config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :employees
  resources :checkinouts
  resources :ref_documents
  resources :leaves, only: [:new, :index]
  root 'employees#index'
  
  get    '/login',   	          to: 'session#new'
  post   '/login',   	          to: 'session#create'
  get 	 '/logout',  	          to: 'session#destroy'
  get 	 '/employees/new',	    to: 'employees#new'
  get 	 '/employees',	        to: 'employees#index'
  get    '/attendances',        to: 'checkinouts#index'
  get    '/lates',              to: 'checkinouts#late_report'
  post   '/leaves/new',         to: 'leaves#create'
  get    '/leave_report',       to: 'leaves#leave_report'
  post   '/deleteDoc',          to: 'employees#deleteDocument'
  post   '/download_pdf',       to: 'employees#download_pdf'
 	
 end

app/views/layouts/_breadcrumb.html.erb
<!-- Breadcrumb-->
<ol class="breadcrumb">
  
<li class="breadcrumb-item"><%= @Home %></li>
<li class="breadcrumb-item">
  <span class="breadcrumb-link"><%= @Link %></span>
</li>
 
</ol>

app/views/layouts/_footer.html.erb
<footer class="app-footer">
  <div>
    <strong>Copyright © 2019 <a href="#">Myanmar High Society Co.,Ltd.</a></strong>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">
  HRMS
  <!-- <img class="navbar-brand-full" src="img/brand/logo.svg" width="89" height="25" alt="CoreUI Logo">
  <img class="navbar-brand-minimized" src="img/brand/sygnet.svg" width="30" height="30" alt="CoreUI Logo"> -->
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show" >
    <span class="navbar-toggler-icon" unless current_page?(login_path)></span>
  </button>
  <ul class="nav navbar-nav ml-auto">
    
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <img class="img-avatar" src="/img/avatars/6.jpg" alt="admin@bootstrapmaster.com">
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
          <strong>Account</strong>
        </div>       
        <a class="dropdown-item" href="#">
          <i class="icon icon-shield"></i> Lock Account</a>
        <a class="dropdown-item" href="<%= logout_path %>">
        <i class="icon icon-logout"></i>Logout
        </a>
      </div>
    </li>
  </ul>
</header>
      

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="nav-icon icon-speedometer"></i> Dashboard
        </a>
      </li>
     <li class="nav-item nav-dropdown <%= 'open' if params[:controller]=='employees' %>">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-user"></i> Employee
        </a>
        <ul class="nav-dropdown-items">
          <li class="nav-item">
            <a class="nav-link pl-4 <%= 'active' if current_page?(new_employee_path) %>" href="/employees/new">
              <i class="nav-icon icon-user-follow"></i> Registration
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link pl-4 <%= 'active' if current_page?(employees_path) %>" href="/employees">
              <i class="nav-icon icon-people"></i> List
            </a>
          </li>
        </ul>
      </li>
      <li class="nav-item nav-dropdown <%= 'open' if params[:controller]=='checkinouts' %>">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-clock"></i> Late Management
        </a>
        <ul class="nav-dropdown-items">
          <li class="nav-item ">
            <a class="nav-link pl-4 <%= 'active' if current_page?(checkinouts_path) %>" href="/checkinouts">
              <i class="nav-icon icon-list"></i>Late Arrival List
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link pl-4 <%= 'active' if current_page?(lates_path) %>" href="/lates">
              <i class="nav-icon icon-docs"></i>Late Arrival Report
            </a>
          </li>      
        </ul>
      </li>

      <li class="nav-item nav-dropdown <%= 'open' if params[:controller]=='leaves' %>">
        <a class="nav-link nav-dropdown-toggle" href="#">
          <i class="nav-icon icon-chart"></i> Leave Management
        </a>
        <ul class="nav-dropdown-items">
          <li class="nav-item ">
            <a class="nav-link <%= 'active' if current_page?(new_leafe_path) %>" href="/leaves/new">
              <i class="nav-icon icon-bell"></i> Apply Leave
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link <%= 'active' if current_page?(leaves_path) %>" href="/leaves">
              <i class="nav-icon icon-book-open"></i> My Leave History
            </a>
          </li>
           <li class="nav-item">
            <a class="nav-link <%= 'active' if current_page?(leave_report_path) %>" href="/leave_report">
              <i class="nav-icon icon-docs"></i> Leave Report
            </a>
          </li>
        </ul>
      </li>
     
    </ul>
  </nav>
    <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>

<script type="text/javascript">

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>HR Management System</title>
    <!-- Icons-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- CoreUI CSS -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>

    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      // Shared ID
      gtag('config', 'UA-118965717-3');
      // Bootstrap ID
      gtag('config', 'UA-118965717-5');
    </script>
  </head>
  <body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
    <%= render 'layouts/header' unless current_page?(login_path) %>
    
     <div class="app-body">
				<%= render 'layouts/sidebar' unless current_page?(login_path) %>
        <main class="main">
        <%= render 'layouts/breadcrumb' unless current_page?(login_path) %>
					<%= yield %>
				</main>
     </div>
    <%= render 'layouts/footer' unless current_page?(login_path) %>
    
   
  </body>
</html>